interface Image {
  AgreementImage?:string ,
  CreatedAt: string ,
  DescriptionImage:string ,
  FirstPageImage:string ,
  Id: string ,
  NurseId: string ,
  Picture: string ,
  UpdatedAt: string ,
}

export default interface NurseInfo {
  Address?: string  ,
  Alley?: string  ,
  Birthday?: string  ,
  BornCity?: string  ,
  ChildPhoneNumber?: string  ,
  City?: string  ,
  CreatedAt?: string  ,
  Education?: string  ,
  FatherName?: string  ,
  Guarantee?: string  ,
  HomeNumber?: string  ,
  HusbandPhoneNumber?: string  ,
  Id: string ,
  Name?: string  ,
  NationalCode?: string  ,
  NationalNumber?: string  ,
  Neighborhood?: string  ,
  NurseCategories: number[] ,
  NurseCategory?: string  ,
  NurseFamily: [] ,
  NurseImages?: Image ,
  OtherProp: null ,
  OtherProps: number[] ,
  ParentPhoneNumber?: string ,
  PhoneNumber?: string  ,
  PostalCode?: string  ,
  Province?: string  ,
  ReserveNurses: [] ,
  Shift: null ,
  Shifts: number[] ,
  SpecialCare: boolean ,
  Street?: string  ,
  Unit?: string  ,
  UpdatedAt?: string  ,
  authority: null ,
  formCode: number ,
  pdfLink?: string  ,
  status?: string  ,
  userId: string ,
}
